-- Create Mexico DB --
CREATE DATABASE MEXICO
GO

-- Create Weather table --

USE MEXICO
CREATE TABLE WEATHER
(
ID INT PRIMARY KEY IDENTITY,
CITY VARCHAR(50) NOT NULL,
HIGH INT NOT NULL,
LOW INT NOT NULL
)

-- Insert new rows --

CREATE PROC INSERTDATA
(
@CITY VARCHAR(50),
@HIGH INT,
@LOW INT
)
AS
INSERT INTO WEATHER
(CITY, HIGH, LOW)
VALUES
(@CITY, @HIGH, @LOW)

EXEC INSERTDATA 'Tijuana', '25', '18'
EXEC INSERTDATA 'Hermosillo', '36', '24'
EXEC INSERTDATA 'La Paz', '33', '23'
EXEC INSERTDATA 'Mazatlan', '29', '22'
EXEC INSERTDATA 'Guadalajara' , '28', '16'
EXEC INSERTDATA 'Acapulco', '30', '24'
EXEC INSERTDATA 'Ciudad Juarez', '33', '19'
EXEC INSERTDATA 'Chihuahua', '32', '17'
EXEC INSERTDATA 'San Luis Potosi', '27', '12'
EXEC INSERTDATA 'Monterrey', '33', '19'
EXEC INSERTDATA 'Ciudad de Mexico', '24', '12'
EXEC INSERTDATA 'Oaxaca', '29', '12'
EXEC INSERTDATA 'Campeche', '30', '22'
EXEC INSERTDATA 'Cancun', '31', '18'

-- Delete duplicates from the table --

CREATE PROC DELETEDUPES
AS
WITH DELDUPE AS (
SELECT CITY,
ROW_NUMBER() OVER (PARTITION BY CITY ORDER BY CITY) AS DUPE
FROM WEATHER
)
DELETE DELDUPE
WHERE DUPE > 1;

EXEC DELETEDUPES

-- Search by City Name --

CREATE PROC SEARCHCITY
@CITY varchar(50)
AS
SELECT * FROM WEATHER
WHERE CITY = @CITY
GO

EXEC SEARCHCITY 'Monterrey'

-- Search for all cities with starting letter --

CREATE PROC SEARCHBYLETTER
@CITY varchar(50) = '%'
AS
SELECT * FROM WEATHER
WHERE CITY LIKE @CITY + '%'
GO

EXEC SEARCHBYLETTER 'M'

-- Search the City with highest temperature --

CREATE PROC MAXTEMP
AS
SELECT ID, CITY, HIGH, LOW 
FROM WEATHER
WHERE HIGH = (SELECT MAX(HIGH) FROM WEATHER);

EXEC MAXTEMP

-- Update data --

CREATE PROC UPDATA
@CITY varchar(50),
@HIGH int,
@LOW int
AS
BEGIN
UPDATE WEATHER SET
HIGH = @HIGH, LOW = @LOW WHERE CITY = @CITY
END

EXEC UPDATA Monterrey, '35', '24'